sudo: false

language: node_js

node_js:
  - node

before_install:
  - go get -v -u github.com/whyrusleeping/gx
  - go get -v -u github.com/metacurrency/holochain
  - cd $GOPATH/src/github.com/metacurrency/holochain
  - git reset --hard origin/dev  # TEMPORARY, UNTIL TEST FIX IS ON MASTER
  - make

script:
  - hc init testbox
  - hc --debug --verbose clone --force . teh
  - hc --debug --verbose test teh

cache:
  directories:
    - $GOPATH/src/gx

notifications:
  slack:
    secure: 0BFyKtWvJG/oMau7gJlsI8NLQXpa1r2orz0Fa09zfcH/qv+aQrwXBUUdp6kYIFsrERDrQMUimjmDc7AwqB1KtTnIztoVPF3S5cWPWIseKksXaN3mZLVYAZwD0n54l0Wq6yy5bnZM7R20pBrPajbqYPIwyX7KfS5bJJ4UKN6i5vI=
