sudo: false

language: go

install: false

before_install:
  - go get -v -u github.com/whyrusleeping/gx
  - go get -v -u github.com/metacurrency/holochain
  - cd $GOPATH/src/github.com/metacurrency/holochain
  - make

script:
  - hc init testing
  - cd $TRAVIS_BUILD_DIR
  - hc --debug --verbose clone --force . teh-test
  - hc --debug --verbose test teh-test

cache:
  directories:
  - "$GOPATH/src/gx"
notifications:
  slack:
    secure: Ctxqpx9sALDCGYi5Xvl+Yx/vLxESVIwB5Jz1C/sHS0R/e4S3yhi48Ufgm1RuA+7YtXIkH7bkD5eGU9Elo2xBdvnF87JugRNrACT1mruuIKg7jUuzRCuN+PVVbCSw8mA4c7iJYz3XEMLdDUvyD2ehyPXIl81EZtwsrAKk3KJNH00WpHmtSwwugU1iBZ+Q+B33aBdvxnsRTgNEGqGtIIpPrahoeltSRjerIQClqVVWAquKIgF3aOvHLJ+cu6qZtvzPMilauaB/iomURyR3GmllosvEquOLIDyJSP+K+dcx1z++MAw3q028blGNIXTZLfIPrGkaUMxs/R+q8urnKmVc1koMHpWDk+NpNoPHpkEkhLPwWKbnjulsHPHC6HtwB2yrB4YzKmQmHDf/q4sy9Zzx9JzYEEB4F5Pm5PH0uM7t772VxR3qtAHAIeOjjG0nOg/FDFjVntgWfPATVHlvMmM0zZltnDJkMrm5B1aztBVWg3LRgbBP8r0MLbJvvpl/DyRh/LubsAj2CS3yWP5uchYFMUYn23DaIQB/ME0YZ0aTgOqaFlTvm/5f/WK5YnI60DFNzWoR7aua/XuFq/XX1TXzE4iiP1tcPKzGbFyviOGBNVNMRpeGQ7fn1FHnWOn8ahOBjRRhD6/9roG5LH31fnR9AM4cUy6U02pEwZUleZxSN/c=
